---
name: CI/CD

"on":
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Run unit tests
        id: unit-tests
        run: |
          just pytest -vv -m "unit" --cov=api \
            --cov-branch \
            --cov-fail-under=80 | tee unit-tests.log

      - name: Build image
        run: |
          just build

  build:
    name: Build Image
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run setup
        uses: ./.github/actions/setup-workspace
        with:
          include-docker: true

      - name: Build image
        run: |
          just build
